language: ruby
rvm:
  - 1.9.3
language: python
python:
  - "2.7"

install:
  - pip install -r ./ci/requirements.txt --use-mirrors
  - sudo apt-get update -q
  - sudo apt-get install -q virtualbox --fix-missing # Everything falls apart here exactly.
  - sh ./ci/install/vagrant.sh
  - sudo vagrant plugin install vagrant-plugin-bundler
script:
  - sudo vagrant up # The error is only presented when executing vagrant up
  - nose2 --verbose
  - sudo vagrant package precise64 --output python-baseline-precise64.box
  - sudo vagrant package precise32 --output python-baseline-precise32.box
  - sudo vagrant package lucid64 --output python-baseline-lucid64.box
  - sudo vagrant package lucid32 --output python-baseline-lucid32.box
after-script:
  - sudo vagrant halt
  - sudo vagrant destroy
