language: ruby
rvm:
  - 1.9.3
language: python
python:
  - "2.7"
before-install:
  - sudo apt-get update -qq
  - apt-get install -qq virtualbox-4.2
install:
  - gem install vagrant
  - pip install -r requirements.txt --use-mirrors
  - vagrant plugin install vagrant-plugin-bundler
script:
  - vagrant up
  - nose2
  - vagrant package python-baseline
after-script:
  - vagrant halt
  - vagrant destroy
