language: ruby
rvm:
  - 1.9.3
language: python
python:
  - "2.7"

install:
  - pip install -r ./ci/requirements.txt --use-mirrors
  - sudo apt-get update -q
  - sudo apt-get install -q virtualbox --fix-missing # Everything falls apart here exactly.
  - sh ./ci/install/vagrant.sh
  - sudo vagrant plugin install vagrant-plugin-bundler
script:
  - sudo vagrant up # The error is only presented when executing vagrant up
  - nose2 --verbose
  - sudo vagrant package python-baseline
after-script:
  - sudo vagrant halt
  - sudo vagrant destroy
